name: ci
run-name: "${{ github.event.head_commit.message || github.event.pull_request.title || github.event.workflow_run.head_commit.message || format('{0} - {1}', github.ref_name, github.event_name) }}"

on:
  push:
    branches-ignore:
      - main
      - 'test/**'
      - 'beta/**'
      - 'dependabot/**'
      - 'renovate/**'
      - 'fix/**'
      - 'feature/**'
      - 'feat/**'
      - 'refactor/**'
      - 'security/**'
  pull_request:
  workflow_run:
    workflows: ["CodeQL"]
    branches:
      - main
      - 'test/**'
      - 'beta/**'
    types:
      - completed
  workflow_dispatch:
    inputs:
      push_image:
        description: 'Push Docker image'
        required: false
        type: boolean
        default: false
  # build weekly for fresh base docker image
  schedule:
    - cron: "30 4 * * 1"

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: false

jobs:
  test:
    name: ci - test (${{ matrix.node-version }})
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run lint
      - run: npm test
      - run: npx c8 --reporter=lcov npm test
      - name: Upload coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: coverage/lcov.info

  build_push:
    name: ci - build, push
    needs: test
    runs-on: ubuntu-latest
    if: always() && needs.test.result == 'success'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
        with:
          ref: ${{ github.event.workflow_run.head_branch || github.ref }}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v6
        with:
          images: |
            bigthundersr/onstar2mqtt 
            ghcr.io/bigthundersr/onstar2mqtt
          flavor: |
            latest=false
          tags: |
            type=ref,event=branch
            type=schedule,pattern=weekly
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v4.0.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to DockerHub
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/test/') || startsWith(github.ref, 'refs/heads/beta/') || (github.event_name == 'workflow_dispatch' && inputs.push_image))
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/test/') || startsWith(github.ref, 'refs/heads/beta/') || (github.event_name == 'workflow_dispatch' && inputs.push_image))
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to DockerHub and GHCR
        uses: docker/build-push-action@v7
        with:
          #platforms: linux/amd64,linux/arm64,linux/arm/v7 #Removed armv7
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' && (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/test/') || startsWith(github.ref, 'refs/heads/beta/') || (github.event_name == 'workflow_dispatch' && inputs.push_image)) }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=OnStarJS wrapper for MQTT
